name: salamina
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - mysqlclient
    - tensorflow
    - numpy
    - pandas
    - mlflow
    - onesaitplatform-client-services
    - mlflow-onesaitplatform-plugin==0.2.9